### ISSUE TITLE
image

### ISSUE THREAD

**Issue by Tauranarora27** [geeklady2/ICT-580-Assignment3#1]

**Comment by geeklady2** [comment]
> _No description provided._

@Tauranarora27  what issue are you reporting?

**Comment by Tauranarora27** [comment]
Dear Shannon,

I am unable to see my contact form page on gitpod.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by geeklady2** [comment]
Try adding something like <a href="../src/contact.html">contact</a> to your code

Note this isn't the right place this, you should send an email.  This is not an issue with this code repository

**Comment by Tauranarora27** [comment]
Madam,

I was not aware that I sent an error report. I just replied to you when saw your email.

Thanks & Regards,
Taruna Arora

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by geeklady2** [comment]
Really weird because the message is not in my email, but it is on GitHub 

It is what it is. I will be closing the issuing on GitHub.

**Comment by Tauranarora27** [comment]
Extremely sorry Shannon, I never meant to raise an issue but it happened by mistake. Accept my apologise.
